# action.yml
name: Github action for rendering rmarkdown files
description: Renders markdown files out of rmarkdown files
author: Robert Warmerdam
inputs:
  input_file:
    description: input rmarkdown file (.Rmd)
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: book
  color: green